### ISSUE TITLE
step 5 code has import problem: $ python utils/generate_data.py Traceback (most recent call last): File "utils/generate_data.py", line 12, in <module> from utils.sunrgbd_config import SUNRGBD_CONFIG ModuleNotFoundError: No module named 'utils' #1

### ISSUE THREAD

**Issue by monacv** [yinyunie/Total3DUnderstanding#27]
```
524/31773MB
[162691:2271 0:713] 06:24:03 Thu Dec 24 [mona@goku:pts/13 +1] ~/research/code/Total3DUnderstanding-Dawnlight
$ ls
total 104K
drwxrwxr-x  5 mona mona 4.0K Dec 24 17:25 ..
-rw-rw-r--  1 mona mona 7.6K Dec 24 17:25 README.md
-rw-rw-r--  1 mona mona 1.1K Dec 24 17:25 LICENSE
drwxrwxr-x  4 mona mona 4.0K Dec 24 17:25 data
-rwxrwxr-x  1 mona mona 9.4K Dec 24 17:25 demo.py
drwxrwxr-x  4 mona mona 4.0K Dec 24 17:25 demo
drwxrwxr-x  4 mona mona 4.0K Dec 24 17:25 external
-rw-rw-r--  1 mona mona 1.5K Dec 24 17:25 environment.yml
-rwxrwxr-x  1 mona mona 1.2K Dec 24 17:25 main.py
-rwxrwxr-x  1 mona mona 2.0K Dec 24 17:25 train.py
-rwxrwxr-x  1 mona mona 3.4K Dec 24 17:25 train_epoch.py
-rwxrwxr-x  1 mona mona 1.4K Dec 24 17:25 test.py
-rwxrwxr-x  1 mona mona 1.6K Dec 24 17:25 test_epoch.py
drwxrwxr-x  8 mona mona 4.0K Dec 24 17:25 .git
-rw-rw-r--  1 mona mona  228 Dec 24 17:30 requirements.txt
drwxrwxr-x  3 mona mona 4.0K Dec 24 17:52 net_utils
drwxrwxr-x  4 mona mona 4.0K Dec 24 17:52 out
drwxrwxr-x  6 mona mona 4.0K Dec 24 17:52 models
drwxrwxr-x  3 mona mona 4.0K Dec 24 17:52 libs
drwxrwxr-x  2 mona mona 4.0K Dec 24 17:52 __pycache__
drwxrwxr-x  3 mona mona 4.0K Dec 24 17:53 utils
drwxrwxr-x  3 mona mona 4.0K Dec 24 17:56 configs
drwxrwxr-x 13 mona mona 4.0K Dec 24 18:17 .
524/31773MB
[162691:2271 0:714] 06:24:06 Thu Dec 24 [mona@goku:pts/13 +1] ~/research/code/Total3DUnderstanding-Dawnlight
$ python utils/generate_data.py
Traceback (most recent call last):
  File "utils/generate_data.py", line 12, in <module>
    from utils.sunrgbd_config import SUNRGBD_CONFIG
ModuleNotFoundError: No module named 'utils'
594/31773MB
[162691:2271 0:715] 06:24:09 Thu Dec 24 [mona@goku:pts/13 +1] ~/research/code/Total3DUnderstanding-Dawnlight

```

**Comment by monacv** [comment]
maybe not the best solution but solved using the following in the beginning of `utils/generate_data.py`
```
import sys
sys.path.append('/home/mona/research/code/Total3DUnderstanding-Dawnlight/')

```
