### ISSUE TITLE
ImportError: No module named 'build'

### ISSUE THREAD

**Issue by frankmecial** [yinyunie/Total3DUnderstanding#47]
i got the following errors

(total3D) G:\Total3DUnderstanding-master>python main.py configs/total3d.yaml --mode train
out\total3d\20221129161655
['external/pyTorchChamferDistance/build']
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from net_utils.utils import initiate_environment
  File "G:\Total3DUnderstanding-master\net_utils\utils.py", line 12, in <module>
    from models.registers import METHODS
  File "G:\Total3DUnderstanding-master\models\__init__.py", line 1, in <module>
    from . import total3d, mgnet
  File "G:\Total3DUnderstanding-master\models\mgnet\__init__.py", line 1, in <module>
    from . import modules, training, config, dataloader
  File "G:\Total3DUnderstanding-master\models\mgnet\config.py", line 5, in <module>
    from .testing import Tester
  File "G:\Total3DUnderstanding-master\models\mgnet\testing.py", line 8, in <module>
    from external.pyTorchChamferDistance.chamfer_distance import ChamferDistance
  File "G:\Total3DUnderstanding-master\external\pyTorchChamferDistance\chamfer_distance\__init__.py", line 1, in <module>
    from .chamfer_distance import ChamferDistance
  File "G:\Total3DUnderstanding-master\external\pyTorchChamferDistance\chamfer_distance\chamfer_distance.py", line 8, in <module>
    build_directory="external/pyTorchChamferDistance/build")
  File "C:\Users\moo-nin\anaconda3\envs\total3D\lib\site-packages\torch\utils\cpp_extension.py", line 644, in load
    is_python_module)
  File "C:\Users\moo-nin\anaconda3\envs\total3D\lib\site-packages\torch\utils\cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\moo-nin\anaconda3\envs\total3D\lib\site-packages\torch\utils\cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\moo-nin\anaconda3\envs\total3D\lib\imp.py", line 298, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'build'

It looks like  some files should in "build" disapper, how to solve this problem?

**Comment by yinyunie** [comment]
Hi,

Have you tried to deploy it on Ubuntu? because this code is developed under Ubuntu 16.04. It should work on any other Ubuntu system.

Best,
Yinyu
