### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by JasonSongPeng** [yinyunie/Total3DUnderstanding#50]
Do you know how to solve this problem?

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    cfg = CONFIG(args.config)
  File "D:\_Python_Respository\Total3DUnderstanding\configs\config_utils.py", line 39, in __init__
    self._logger, self._save_path = self.load_logger()
  File "D:\_Python_Respository\Total3DUnderstanding\configs\config_utils.py", line 65, in load_logger
    os.makedirs(save_path)
  File "C:\Anaconda3\envs\Total3D\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'out/total3d\\2023-06-13T11:09:46.665278'

**Comment by GG-nome** [comment]
我也遇到这个问题了 请问你是怎么解决的
